# services:
#   # The name of the service must match the full namespace class
#   Knytify\Controller\GettingStartedController:
#     class: Knytify\Controller\GettingStartedController
#     arguments:
#       - '@doctrine.cache.provider'
