
knytify_configuration:
    path: knytify/configuration
    methods: [GET]
    defaults:
        _controller: 'Knytify\Controller\Admin\ConfigurationController::indexAction'
        _legacy_controller: "KnytifyConfiguration"
        _legacy_link: KnytifyConfiguration

knytify_stats:
    path: knytify/stats
    methods: [GET]
    defaults:
        _controller: 'Knytify\Controller\Admin\StatsController::indexAction'
        _legacy_controller: "KnytifyStats"
        _legacy_link: KnytifyStats

knytify_error:
    path: knytify/error
    methods: [GET]
    defaults:
        _controller: 'Knytify\Controller\Admin\ErrorController::indexAction'
        _legacy_controller: "KnytifyError"
        _legacy_link: KnytifyError

#################
# Rest Routes
#################

ps_knytify_configuration_set:
    path: knytify/rest/configuration
    methods: [POST]
    defaults:
        _controller: 'Knytify\Controller\Admin\ConfigurationController::setConfig'

ps_knytify_configuration_get:
    path: knytify/rest/configuration
    methods: [GET]
    defaults:
        _controller: 'Knytify\Controller\Admin\ConfigurationController::getConfig'


ps_knytify_configuration_script_set:
    path: knytify/rest/configuration-script
    methods: [POST]
    defaults:
        _controller: 'Knytify\Controller\Admin\ConfigurationController::setScriptConfig'

ps_knytify_configuration_script_get:
    path: knytify/rest/configuration-script
    methods: [GET]
    defaults:
        _controller: 'Knytify\Controller\Admin\ConfigurationController::getScriptConfig'

ps_knytify_stats:
    path: knytify/rest/stats
    methods: [GET]
    defaults:
        _controller: 'Knytify\Controller\Admin\StatsController::indexAction'
        _legacy_controller: "KnytifyStats"
        _legacy_link: KnytifyStats

ps_knytify_stats_recap:
    path: knytify/rest/stats-recap
    methods: [GET]
    defaults:
        _controller: 'Knytify\Controller\Admin\StatsController::recap'

ps_knytify_stats_advanced:
    path: knytify/rest/tats-advanced
    methods: [GET]
    defaults:
        _controller: 'Knytify\Controller\Admin\StatsController::advanced'
