ps_controller_getting_started:
    path: knytify/getting-started
    methods: [GET]
    defaults:
        _controller: 'Knytify\Controller\Admin\GettingStartedController::indexAction'
        _legacy_controller: "KnytifyGettingStarted"
        _legacy_link: KnytifyGettingStarted

ps_controller_registration:
    path: knytify/registration
    methods: [GET, POST]
    defaults:
        _controller: 'Knytify\Controller\Admin\RegistrationController::indexAction'
        _legacy_controller: "KnytifyRegistration"
        _legacy_link: KnytifyRegistration

ps_controller_login:
    path: knytify/login
    methods: [GET, POST]
    defaults:
        _controller: 'Knytify\Controller\Admin\LoginController::indexAction'
        _legacy_controller: "KnytifyLogin"
        _legacy_link: KnytifyLogin

ps_controller_api_key:
    path: knytify/api-key
    methods: [GET, POST]
    defaults:
        _controller: 'Knytify\Controller\Admin\ApiKeyController::indexAction'
        _legacy_controller: "KnytifyApiKey"
        _legacy_link: KnytifyApiKey

ps_controller_configuration:
    path: knytify/configuration
    methods: [GET, POST]
    defaults:
        _controller: 'Knytify\Controller\Admin\ConfigurationController::indexAction'
        _legacy_controller: "KnytifyConfiguration"
        _legacy_link: KnytifyConfiguration

ps_controller_stats:
    path: knytify/stats
    methods: [GET]
    defaults:
        _controller: 'Knytify\Controller\Admin\StatsController::indexAction'
        _legacy_controller: "KnytifyStats"
        _legacy_link: KnytifyStats


ps_controller_error:
    path: knytify/error
    methods: [GET]
    defaults:
        _controller: 'Knytify\Controller\Admin\ErrorController::indexAction'
        _legacy_controller: "KnytifyError"
        _legacy_link: KnytifyError